# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/a3y17lte/setup-makefiles.sh

LOCAL_PATH := vendor/samsung/a3y17lte/proprietary/

PRODUCT_COPY_FILES += \
$(LOCAL_PATH)app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
$(LOCAL_PATH)app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
$(LOCAL_PATH)app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
$(LOCAL_PATH)app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
$(LOCAL_PATH)app/mcRegistry/08130000000000000000000000000000.tlbin:system/app/mcRegistry/08130000000000000000000000000000.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff00000000000000000000000b.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff000000000000000000000019.tlbin:system/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff00000000000000000000001f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000001f.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff00000000000000000000002e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000002e.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff000000000000000000000030.tlbin:system/app/mcRegistry/ffffffff000000000000000000000030.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff000000000000000000000041.tlbin:system/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffff000000000000000000000045.tlbin:system/app/mcRegistry/ffffffff000000000000000000000045.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffffd00000000000000000000014.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000014.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
$(LOCAL_PATH)app/mcRegistry/ffffffffd00000000000000000000017.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000017.tlbin \
$(LOCAL_PATH)app/mcRegistry/fffffffff0000000000000000000001b.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001b.tlbin \
$(LOCAL_PATH)app/mcRegistry/fffffffff0000000000000000000001e.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001e.tlbin \
$(LOCAL_PATH)bin/gpsd:system/bin/gpsd \
$(LOCAL_PATH)bin/mcDriverDaemon:system/bin/mcDriverDaemon \
$(LOCAL_PATH)bin/prepare_param.sh:system/bin/prepare_param.sh \
$(LOCAL_PATH)bin/sensorhubservice:system/bin/sensorhubservice \
$(LOCAL_PATH)bin/wcnss_filter:system/bin/wcnss_filter \
$(LOCAL_PATH)etc/Tfa9896.cnt:system/etc/Tfa9896.cnt \
$(LOCAL_PATH)etc/bluetooth/av_performance.conf:system/etc/bluetooth/av_performance.conf \
$(LOCAL_PATH)etc/bluetooth/bt_did.conf:system/etc/bluetooth/bt_did.conf \
$(LOCAL_PATH)etc/bluetooth/bt_stack.conf:system/etc/bluetooth/bt_stack.conf \
$(LOCAL_PATH)etc/bluetooth/iop_bt.db:system/etc/bluetooth/iop_bt.db \
$(LOCAL_PATH)etc/bluetooth/iop_device_list.conf:system/etc/bluetooth/iop_device_list.conf \
$(LOCAL_PATH)etc/ca.pem:system/etc/ca.pem \
$(LOCAL_PATH)etc/firmware/Data.msc:system/etc/firmware/Data.msc \
$(LOCAL_PATH)etc/firmware/bdwlan30.bin:system/etc/firmware/bdwlan30.bin \
$(LOCAL_PATH)etc/firmware/bdwlan32.bin:system/etc/firmware/bdwlan32.bin \
$(LOCAL_PATH)etc/firmware/nvm_tlv.bin:system/etc/firmware/nvm_tlv.bin \
$(LOCAL_PATH)etc/firmware/nvm_tlv_1.3.bin:system/etc/firmware/nvm_tlv_1.3.bin \
$(LOCAL_PATH)etc/firmware/nvm_tlv_2.1.bin:system/etc/firmware/nvm_tlv_2.1.bin \
$(LOCAL_PATH)etc/firmware/nvm_tlv_3.0.bin:system/etc/firmware/nvm_tlv_3.0.bin \
$(LOCAL_PATH)etc/firmware/nvm_tlv_3.2.bin:system/etc/firmware/nvm_tlv_3.2.bin \
$(LOCAL_PATH)etc/firmware/nvm_tlv_tf_1.1.bin:system/etc/firmware/nvm_tlv_tf_1.1.bin \
$(LOCAL_PATH)etc/firmware/otp30.bin:system/etc/firmware/otp30.bin \
$(LOCAL_PATH)etc/firmware/qwlan30.bin:system/etc/firmware/qwlan30.bin \
$(LOCAL_PATH)etc/firmware/qwlan30_ibss.bin:system/etc/firmware/qwlan30_ibss.bin \
$(LOCAL_PATH)etc/firmware/rampatch_tlv.img:system/etc/firmware/rampatch_tlv.img \
$(LOCAL_PATH)etc/firmware/rampatch_tlv_1.3.tlv:system/etc/firmware/rampatch_tlv_1.3.tlv \
$(LOCAL_PATH)etc/firmware/rampatch_tlv_2.1.tlv:system/etc/firmware/rampatch_tlv_2.1.tlv \
$(LOCAL_PATH)etc/firmware/rampatch_tlv_3.0.tlv:system/etc/firmware/rampatch_tlv_3.0.tlv \
$(LOCAL_PATH)etc/firmware/rampatch_tlv_3.2.tlv:system/etc/firmware/rampatch_tlv_3.2.tlv \
$(LOCAL_PATH)etc/firmware/rampatch_tlv_tf_1.1.tlv:system/etc/firmware/rampatch_tlv_tf_1.1.tlv \
$(LOCAL_PATH)etc/firmware/utf30.bin:system/etc/firmware/utf30.bin \
$(LOCAL_PATH)etc/firmware/utfbd30.bin:system/etc/firmware/utfbd30.bin \
$(LOCAL_PATH)etc/firmware/utfbd32.bin:system/etc/firmware/utfbd32.bin \
$(LOCAL_PATH)etc/plmn_delta.bin:system/etc/plmn_delta.bin \
$(LOCAL_PATH)etc/plmn_se13.bin:system/etc/plmn_se13.bin \
$(LOCAL_PATH)etc/sec_s3nrn80_rfreg.bin:system/etc/sec_s3nrn80_rfreg.bin \
$(LOCAL_PATH)etc/somxreg.conf:system/etc/somxreg.conf \
$(LOCAL_PATH)etc/srm.bin:system/etc/srm.bin \
$(LOCAL_PATH)lib/egl/egl.cfg:system/lib/egl/egl.cfg \
$(LOCAL_PATH)lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
$(LOCAL_PATH)lib/hw/camera.universal7870.so:system/lib/hw/camera.universal7870.so \
$(LOCAL_PATH)lib/hw/gps.default.so:system/lib/hw/gps.default.so \
$(LOCAL_PATH)lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
$(LOCAL_PATH)lib/hw/sensorhubs.universal7870.so:system/lib/hw/sensorhubs.universal7870.so \
$(LOCAL_PATH)lib/hw/sensors.universal7870.so:system/lib/hw/sensors.universal7870.so \
$(LOCAL_PATH)lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
$(LOCAL_PATH)lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
$(LOCAL_PATH)lib/libHpr_RecFace_dl_v1.0.so:system/lib/libHpr_RecFace_dl_v1.0.so \
$(LOCAL_PATH)lib/libHpr_RecGAE_cvFeature_v1.0.so:system/lib/libHpr_RecGAE_cvFeature_v1.0.so \
$(LOCAL_PATH)lib/libHpr_TaskFaceClustering_hierarchical_v1.0.so:system/lib/libHpr_TaskFaceClustering_hierarchical_v1.0.so \
$(LOCAL_PATH)lib/libarac.so:system/lib/libarac.so \
$(LOCAL_PATH)lib/libaudio-ril.so:system/lib/libaudio-ril.so \
$(LOCAL_PATH)lib/libbauthserver.so:system/lib/libbauthserver.so \
$(LOCAL_PATH)lib/libbauthtzcommon.so:system/lib/libbauthtzcommon.so \
$(LOCAL_PATH)lib/libcsc.so:system/lib/libcsc.so \
$(LOCAL_PATH)lib/libegis_fp_normal_sensor_test.so:system/lib/libegis_fp_normal_sensor_test.so \
$(LOCAL_PATH)lib/libexynoscamera.so:system/lib/libexynoscamera.so \
$(LOCAL_PATH)lib/libexynoscamera3.so:system/lib/libexynoscamera3.so \
$(LOCAL_PATH)lib/libexynosgscaler.so:system/lib/libexynosgscaler.so \
$(LOCAL_PATH)lib/libexynosscaler.so:system/lib/libexynosscaler.so \
$(LOCAL_PATH)lib/libexynosutils.so:system/lib/libexynosutils.so \
$(LOCAL_PATH)lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
$(LOCAL_PATH)lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
$(LOCAL_PATH)lib/libhwjpeg.so:system/lib/libhwjpeg.so \
$(LOCAL_PATH)lib/libprotobuf-cpp-N.so:system/lib/libprotobuf-cpp-N.so \
$(LOCAL_PATH)lib/libprotobuf-cpp-fooo.so:system/lib/libprotobuf-cpp-fooo.so \
$(LOCAL_PATH)lib/libreference-ril.so:system/lib/libreference-ril.so \
$(LOCAL_PATH)lib/librilutils.so:system/lib/librilutils.so \
$(LOCAL_PATH)lib/libsavsac.so:system/lib/libsavsac.so \
$(LOCAL_PATH)lib/libsavscmn.so:system/lib/libsavscmn.so \
$(LOCAL_PATH)lib/libsavsff.so:system/lib/libsavsff.so \
$(LOCAL_PATH)lib/libsavsmeta.so:system/lib/libsavsmeta.so \
$(LOCAL_PATH)lib/libsavsvc.so:system/lib/libsavsvc.so \
$(LOCAL_PATH)lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so \
$(LOCAL_PATH)/lib/libsec-ril.so:system/lib/libsec-ril.so \
$(LOCAL_PATH)lib/libseccameracore.so:system/lib/libseccameracore.so \
$(LOCAL_PATH)lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
$(LOCAL_PATH)lib/libsecril-client.so:system/lib/libsecril-client.so \
$(LOCAL_PATH)lib/libsensorhub.so:system/lib/libsensorhub.so \
$(LOCAL_PATH)lib/libsensorhubservice.so:system/lib/libsensorhubservice.so \
$(LOCAL_PATH)lib/libsensorlistener.so:system/lib/libsensorlistener.so \
$(LOCAL_PATH)lib/libsensorservice.so:system/lib/libsensorservice.so \
$(LOCAL_PATH)lib/libsnaace.so:system/lib/libsnaace.so \
$(LOCAL_PATH)lib/libsnamrnb.so:system/lib/libsnamrnb.so \
$(LOCAL_PATH)lib/libsnamrwb.so:system/lib/libsnamrwb.so \
$(LOCAL_PATH)lib/libsomx263dsw.so:system/lib/libsomx263dsw.so \
$(LOCAL_PATH)lib/libsomx264dsw.so:system/lib/libsomx264dsw.so \
$(LOCAL_PATH)lib/libsomxaacd.so:system/lib/libsomxaacd.so \
$(LOCAL_PATH)lib/libsomxaace.so:system/lib/libsomxaace.so \
$(LOCAL_PATH)lib/libsomxadpcmd.so:system/lib/libsomxadpcmd.so \
$(LOCAL_PATH)lib/libsomxamrd.so:system/lib/libsomxamrd.so \
$(LOCAL_PATH)lib/libsomxevrcd.so:system/lib/libsomxevrcd.so \
$(LOCAL_PATH)lib/libsomxevrce.so:system/lib/libsomxevrce.so \
$(LOCAL_PATH)lib/libsomxflacd.so:system/lib/libsomxflacd.so \
$(LOCAL_PATH)lib/libsomxhevcdsw.so:system/lib/libsomxhevcdsw.so \
$(LOCAL_PATH)lib/libsomxmp3d.so:system/lib/libsomxmp3d.so \
$(LOCAL_PATH)lib/libsomxmp43d.so:system/lib/libsomxmp43d.so \
$(LOCAL_PATH)lib/libsomxmp4vdsw.so:system/lib/libsomxmp4vdsw.so \
$(LOCAL_PATH)lib/libsomxnaace.so:system/lib/libsomxnaace.so \
$(LOCAL_PATH)lib/libsomxqcelpd.so:system/lib/libsomxqcelpd.so \
$(LOCAL_PATH)lib/libsomxqcelpe.so:system/lib/libsomxqcelpe.so \
$(LOCAL_PATH)lib/libsomxsr263d.so:system/lib/libsomxsr263d.so \
$(LOCAL_PATH)lib/libsomxvc1dsw.so:system/lib/libsomxvc1dsw.so \
$(LOCAL_PATH)lib/libsomxvp8d.so:system/lib/libsomxvp8d.so \
$(LOCAL_PATH)lib/libsomxwmad.so:system/lib/libsomxwmad.so \
$(LOCAL_PATH)lib/libsomxwmv7d.so:system/lib/libsomxwmv7d.so \
$(LOCAL_PATH)lib/libsomxwmv8d.so:system/lib/libsomxwmv8d.so \
$(LOCAL_PATH)lib/libstainkiller.so:system/lib/libstainkiller.so \
$(LOCAL_PATH)lib/libsxqk.so:system/lib/libsxqk.so \
$(LOCAL_PATH)lib/libsynaFpSensorTestNwd.so:system/lib/libsynaFpSensorTestNwd.so \
$(LOCAL_PATH)lib/libuniplugin.so:system/lib/libuniplugin.so \
$(LOCAL_PATH)lib/libwrappergps.so:system/lib/libwrappergps.so \
$(LOCAL_PATH)lib/modules/qca_cld/qca_cld_wlan.ko:system/lib/modules/qca_cld/qca_cld_wlan.ko \
$(LOCAL_PATH)lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
$(LOCAL_PATH)lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
$(LOCAL_PATH)lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
$(LOCAL_PATH)lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
$(LOCAL_PATH)lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
$(LOCAL_PATH)lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
$(LOCAL_PATH)lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
$(LOCAL_PATH)lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
$(LOCAL_PATH)lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
$(LOCAL_PATH)vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
$(LOCAL_PATH)vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
$(LOCAL_PATH)vendor/firmware/setfile_imx219.bin:system/vendor/firmware/setfile_imx219.bin \
$(LOCAL_PATH)vendor/firmware/setfile_imx258.bin:system/vendor/firmware/setfile_imx258.bin \
$(LOCAL_PATH)vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
$(LOCAL_PATH)vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
$(LOCAL_PATH)vendor/lib/libHpr_LocFace_mvfd_v1.0.so:system/vendor/lib/libHpr_LocFace_mvfd_v1.0.so \
$(LOCAL_PATH)vendor/lib/libHpr_LocLandmark_sdm_v1.0.so:system/vendor/lib/libHpr_LocLandmark_sdm_v1.0.so \
$(LOCAL_PATH)vendor/lib/soundfx/libLifevibes_lvverx.so:system/vendor/lib/soundfx/libLifevibes_lvverx.so \
$(LOCAL_PATH)vendor/lib/soundfx/libLifevibes_lvvetx.so:system/vendor/lib/soundfx/libLifevibes_lvvetx.so \
$(LOCAL_PATH)lib/libMcClient.so:system/lib/libMcClient.so \
$(LOCAL_PATH)lib/libMcRegistry.so:system/lib/libMcRegistry.so \
$(LOCAL_PATH)lib/libOpenCv.so:system/lib/libOpenCv.so \
$(LOCAL_PATH)vendor/lib/libSEF.so:system/vendor/lib/libSEF.so \
$(LOCAL_PATH)vendor/lib/libflp.so:system/vendor/lib/libflp.so \
$(LOCAL_PATH)lib/libsomp.so:system/lib/libsomp.so \
$(LOCAL_PATH)vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so
