# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/a3y17lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/a3y17lte/proprietary/lib/libtfa98xx.so:system/lib/libtfa98xx.so \
    vendor/samsung/a3y17lte/proprietary/etc/Tfa9896.cnt:system/etc/Tfa9896.cnt \
    vendor/samsung/a3y17lte/proprietary/bin/wcnss_filter:system/bin/wcnss_filter \
    vendor/samsung/a3y17lte/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/samsung/a3y17lte/proprietary/lib/hw/camera.universal7870.so:system/lib/hw/camera.universal7870.so \
    vendor/samsung/a3y17lte/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/a3y17lte/proprietary/lib/libexynoscamera3.so:system/lib/libexynoscamera3.so \
    vendor/samsung/a3y17lte/proprietary/lib/libuniapi.so:system/lib/libuniapi.so \
    vendor/samsung/a3y17lte/proprietary/lib/libuniplugin.so:system/lib/libuniplugin.so \
    vendor/samsung/a3y17lte/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/a3y17lte/proprietary/vendor/firmware/setfile_3p8_front.bin:system/vendor/firmware/setfile_3p8_front.bin \
    vendor/samsung/a3y17lte/proprietary/vendor/firmware/setfile_3p8.bin:system/vendor/firmware/setfile_3p8.bin \
    vendor/samsung/a3y17lte/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/a3y17lte/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/a3y17lte/proprietary/lib/libbauthserver.so:system/lib/libbauthserver.so \
    vendor/samsung/a3y17lte/proprietary/lib/libbauthtzcommon.so:system/lib/libbauthtzcommon.so \
    vendor/samsung/a3y17lte/proprietary/lib/libegis_fp_normal_sensor_test.so:system/lib/libegis_fp_normal_sensor_test.so \
    vendor/samsung/a3y17lte/proprietary/lib/libsynaFpSensorTestNwd.so:system/lib/libsynaFpSensorTestNwd.so \
    vendor/samsung/a3y17lte/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/a3y17lte/proprietary/etc/ca.pem:system/etc/ca.pem \
    vendor/samsung/a3y17lte/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/a3y17lte/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/a3y17lte/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/a3y17lte/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/a3y17lte/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/a3y17lte/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/a3y17lte/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/08130000000000000000000000000000.tlbin:system/app/mcRegistry/08130000000000000000000000000000.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000000b.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000019.tlbin:system/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000001f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000001f.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff00000000000000000000002e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000002e.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000030.tlbin:system/app/mcRegistry/ffffffff000000000000000000000030.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000041.tlbin:system/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffff000000000000000000000045.tlbin:system/app/mcRegistry/ffffffff000000000000000000000045.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffffd00000000000000000000014.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000014.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/ffffffffd00000000000000000000017.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000017.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/fffffffff0000000000000000000001b.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001b.tlbin \
    vendor/samsung/a3y17lte/proprietary/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001e.tlbin \
    vendor/samsung/a3y17lte/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    vendor/samsung/a3y17lte/proprietary/lib/libMcClient.so:system/lib/libMcClient.so \
    vendor/samsung/a3y17lte/proprietary/lib/libMcRegistry.so:system/lib/libMcRegistry.so \
    vendor/samsung/a3y17lte/proprietary/etc/nfc/sec_s3nrn80_rfreg.bin:system/etc/nfc/sec_s3nrn80_rfreg.bin \
    vendor/samsung/a3y17lte/proprietary/lib/hw/nfc_nci.universal7870.so:system/lib/hw/nfc_nci.universal7870.so \
    vendor/samsung/a3y17lte/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/a3y17lte/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/a3y17lte/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/a3y17lte/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/a3y17lte/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/a3y17lte/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/a3y17lte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/a3y17lte/proprietary/lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so \
    vendor/samsung/a3y17lte/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/a3y17lte/proprietary/bin/sensorhubservice:system/bin/sensorhubservice \
    vendor/samsung/a3y17lte/proprietary/lib/hw/sensors.universal7870.so:system/lib/hw/sensors.universal7870.so \
    vendor/samsung/a3y17lte/proprietary/lib/hw/sensorhubs.universal7870.so:system/lib/hw/sensorhubs.universal7870.so \
    vendor/samsung/a3y17lte/proprietary/lib/libsensorhub.so:system/lib/libsensorhub.so \
    vendor/samsung/a3y17lte/proprietary/lib/libsensorhubservice.so:system/lib/libsensorhubservice.so \
    vendor/samsung/a3y17lte/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
    vendor/samsung/a3y17lte/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/bdwlan30.bin:system/etc/firmware/bdwlan30.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/bdwlan30_OLD.bin:system/etc/firmware/bdwlan30_OLD.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/bdwlan32.bin:system/etc/firmware/bdwlan32.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/otp30.bin:system/etc/firmware/otp30.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/qwlan30.bin:system/etc/firmware/qwlan30.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/qwlan30_ibss.bin:system/etc/firmware/qwlan30_ibss.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/Data.msc:system/etc/firmware/Data.msc \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/nvm_tlv.bin:system/etc/firmware/nvm_tlv.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/nvm_tlv_1.3.bin:system/etc/firmware/nvm_tlv_1.3.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/nvm_tlv_2.1.bin:system/etc/firmware/nvm_tlv_2.1.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/nvm_tlv_3.0.bin:system/etc/firmware/nvm_tlv_3.0.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/nvm_tlv_3.2.bin:system/etc/firmware/nvm_tlv_3.2.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/nvm_tlv_tf_1.1.bin:system/etc/firmware/nvm_tlv_tf_1.1.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/rampatch_tlv.img:system/etc/firmware/rampatch_tlv.img \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/rampatch_tlv_1.3.tlv:system/etc/firmware/rampatch_tlv_1.3.tlv \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/rampatch_tlv_2.1.tlv:system/etc/firmware/rampatch_tlv_2.1.tlv \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/rampatch_tlv_3.0.tlv:system/etc/firmware/rampatch_tlv_3.0.tlv \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/rampatch_tlv_3.2.tlv:system/etc/firmware/rampatch_tlv_3.2.tlv \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/rampatch_tlv_tf_1.1.tlv:system/etc/firmware/rampatch_tlv_tf_1.1.tlv \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/utf30.bin:system/etc/firmware/utf30.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/utfbd30.bin:system/etc/firmware/utfbd30.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/utfbd30_OLD.bin:system/etc/firmware/utfbd30_OLD.bin \
    vendor/samsung/a3y17lte/proprietary/etc/firmware/utfbd32.bin:system/etc/firmware/utfbd32.bin \
    vendor/samsung/a3y17lte/proprietary/lib/modules/qca_cld/qca_cld_wlan.ko:system/lib/modules/qca_cld/qca_cld_wlan.ko
